version: '3.8'

services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ../user-service:/usr/src/app

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: